name: Run Jupyter Notebook and Generate HTML

on:
  push:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert numpy flask pandas


      - name: Run Jupyter Notebook
        run: |
            mkdir -p output/output/1_Prep_sessions
            jupyter nbconvert --to notebook --execute 1_Prep_sessions/1_1_ML_C41_Python_Crash_Course.ipynb --output ../output/output/1_Prep_sessions/1_1_ML_C41_Python_Crash_Course.ipynb
            jupyter nbconvert --to notebook --execute 1_Prep_sessions/1_3_Data_science_Numpy.ipynb --output ../output/output/1_Prep_sessions/1_3_Data_science_Numpy.ipynb
            #jupyter nbconvert --to notebook --execute 1_Prep_sessions/1_3_Data_science_Pandas.ipynb --output ../output/output/1_Prep_sessions/1_3_Data_science_Pandas.ipynb

      - name: Convert Executed Notebook to HTML
        run: |
            jupyter nbconvert --to html output/output/1_Prep_sessions/1_1_ML_C41_Python_Crash_Course.ipynb --output 1_1_ML_C41_Python_Crash_Course
            jupyter nbconvert --to html output/output/1_Prep_sessions/1_3_Data_science_Numpy.ipynb --output 1_3_Data_science_Numpy
            #jupyter nbconvert --to html output/output/1_Prep_sessions/1_3_Data_science_Pandas.ipynb --output 1_3_Data_science_Pandas

      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            output/