name: Run Jupyter Notebook and Generate HTML

on:
  push:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          #pip install jupyter nbconvert ipython numpy pandas seaborn matplotlib plotly imblearn xgboost


      - name: Run .py files
        run: |
          #cd 2_Course_continuation/_2_Exam_2/3_Machine_learning_2/8_Telecom_Churn_Group_Case_Study
          #ipython Tel-Chrn-muni-old.py
          #ipython Telecom+Churn+_+ML+Group+Case+Study.py
