name: Run Jupyter Notebook and Generate HTML

on:
  push:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert numpy flask


      - name: Run Jupyter Notebook
        run: |
            jupyter nbconvert --to notebook --execute 1_Prep_sessions/1_1_ML_C41_Python_Crash_Course.ipynb --output output/1_1_ML_C41_Python_Crash_Course_output.ipynb


      - name: Convert Executed Notebook to HTML
        run: |
            jupyter nbconvert --to html 1_Prep_sessions/output/1_1_ML_C41_Python_Crash_Course_output.ipynb --output 1_1_ML_C41_Python_Crash_Course_output


      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            # 1_Prep_sessions/1_1_ML_C41_Python_Crash_Course_output.ipynb
            # 1_Prep_sessions/1_1_ML_C41_Python_Crash_Course_output.html
            1_Prep_sessions/output